sugarcube-2:
  macros:
    FluffyDesc:
      name: FluffyDesc
    inlineColor:
      name: inlineColor
    They:
      name: They
    colorizeText:
      name: colorizeText
    fetchName:
      name: fetchName
    displayAttribute:
      name: displayAttribute
    displayStat:
      name: displayStat
    Their:
      name: Their
    PlayerStatus:
      name: PlayerStatus
    fluffyImage:
      name: fluffyImage
    colorGroup:
      name: colorGroup
    statValue:
      name: statValue
    newFoal:
      name: newFoal
    colorValue:
      name: colorValue
    newFromGene:
      name: newFromGene
    BaseFluffy:
      name: BaseFluffy
    OptionsWidget:
      name: OptionsWidget
    limitColor:
      name: limitColor
    setGeneTraits:
      name: setGeneTraits
    shortDesc:
      name: shortDesc
    sidebarTop:
      name: sidebarTop
    systemButtons:
      name: systemButtons
    updateStoreButtons:
      name: updateStoreButtons
    SidebarStore:
      name: SidebarStore
    sortButtons:
      name: sortButtons
    FluffyList:
      name: FluffyList
    intractDetails:
      name: intractDetails
    SidebarButton:
      name: SidebarButton
    fluffSpeech:
      name: fluffSpeech
    removeFluffy:
      name: removeFluffy
    talkySprite:
      name: talkySprite
    adultSprite:
      name: adultSprite
    greySprite:
      name: greySprite
    chirpySprite:
      name: chirpySprite
    newbornSprite:
      name: newbornSprite
    youthSprite:
      name: youthSprite
    foalSprite:
      name: foalSprite
    checkvars:
      name: checkvars
    bugreport:
      name: bugreport
    iconSprite:
      name: iconSprite
    displayPrice:
      name: displayPrice
    OfferFluffy:
      name: OfferFluffy
    econDesc:
      name: econDesc
    introButton:
      name: introButton
    alicornDesc2:
      name: alicornDesc2
    alicornDesc:
      name: alicornDesc
    poopDesc:
      name: poopDesc
    smartDesc:
      name: smartDesc
    shopUpdate:
      name: shopUpdate
    SidebarFluffies:
      name: SidebarFluffies
    SidebarCash:
      name: SidebarCash
    breedFluffies:
      name: breedFluffies
    deadFluffy:
      name: deadFluffy
    clampValues:
      name: clampValues
    cashAdd:
      name: cashAdd
    cashClamp:
      name: cashClamp
    cashMinus:
      name: cashMinus
