openapi: 3.0.1
info:
  title: Fluffy Breeder
  description: 'A text-based fluffy management game.'
  termsOfService: https://github.com/eidalac/FluffyBreeder
  contact: 
    email: eidalac@gmail.com
  license:
    name: GNU General Public License 3.0
    url: https://www.gnu.org/licenses/gpl-3.0.htmls
  version: 0.1.14
externalDocs:
  description: GitHub
  url: https://github.com/eidalac/FluffyBreeder
tags:
- name: pet
  description: Everything about your Pets
  externalDocs:
    description: Find out more
    url: http://swagger.io
- name: store
  description: Access to Petstore orders
- name: user
  description: Operations about user
  externalDocs:
    description: Find out more about our store
    url: http://swagger.io
components:
  schemas:
    fluffyImage:
      type: object
      properties:
        newbornSprite:
          type: object